version: "3"

services:

  runtime-setup:
    image: swift-package-registry-compat-test-suite:18.04-5.4
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.4"

  test-registry:
    image: swift-package-registry-compat-test-suite:18.04-5.4

  shell:
    image: swift-package-registry-compat-test-suite:18.04-5.4
